language: haskell

ghc: 7.8

addons:
 apt:
  packages:
   - libgtk-3-dev
   - libgtk2.0-dev
before_install:
  - cabal install gtk2hs-buildtools
  - cabal install --only-dependencies --enable-tests --force-reinstalls
