language: haskell

ghc: 7.8

addons:
 apt:
  sources:
   - hvr-ghc
  packages:
   - ghc-7.10.1
   - cabal-install-1.22
   - libgtk-3-dev
   - libgtk2.0-dev
before_install:
  - cabal install gtk2hs-buildtools
  - cabal install --only-dependencies --enable-tests --force-reinstalls
