language: haskell

ghc: 7.8

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.22
      - libgtk-3-dev
      - libgtk2.0-dev

before_install:
  - export PATH=$PATH:/opt/cabal/1.22/bin
  - travis_retry cabal update
  - export PATH=$PATH:$PWD/.cabal/bin/
  - env
  - cabal install gtk2hs-buildtools
  - cabal install --only-dependencies --enable-tests --force-reinstalls
