language: haskell

ghc: 7.8

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - alex-3.1.4
      - happy-1.19.5

before_install:
  ## A recent version of alex and happy is requeired to build gtk2hs-buildtools
  - export PATH=/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
  
  ## It is not pulled in as a dependency (its installation destination is
  ## already in PATH)
  - cabal install gtk2hs-buildtools
  - cabal install --only-dependencies --enable-tests --force-reinstalls
