language: haskell

ghc: 7.8

addons:
 apt:
  sources:
  - hvr-ghc
  packages:
   - libgtk-3-dev
   - libgtk2.0-dev
before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
  - travis_retry cabal update
  - export PATH=$PATH:$PWD/.cabal/bin/
  - cabal install Cabal
  - cabal install gtk2hs-buildtools
  - cabal install --only-dependencies --enable-tests --force-reinstalls
