language: haskell

ghc: 7.8

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - alex-3.1.4
      - happy-1.19.5
      #- libgtk-3-dev
      - libgtk2.0-dev

before_install:
  - export PATH=/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
  - cabal install gtk2hs-buildtools
  - cabal install --only-dependencies --enable-tests --force-reinstalls
