language: haskell
sudo: false
ghc: 7.8
before_install:
  - travis_retry cabal update
  - export PATH=$PATH:$PWD/.cabal/bin/
  - pwd
  - env
  - cabal install Cabal
  - cabal install gtk2hs-buildtools-0.12.5.1
